springdoc:
  version: 'v1'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
#  paths-to-match:
#    - /api/**